### ISSUE TITLE
Error authenticating with Jira

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/jira-tool#6]
Of course, the code will fail now as we don't yet use OAuth

```
Caused by: RestClientException{statusCode=Optional.of(401), errorCollections=[]}
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:178)
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:170)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:67)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:11)
        at com.atlassian.util.concurrent.Promises$Of$3.apply(Promises.java:295)
        at com.atlassian.util.concurrent.Promises$2.onSuccess(Promises.java:185)
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
...
 <div class="aui-message aui-message-warning warning">
                            <p>Encountered a <code>&quot;401 - Unauthorized&quot;</code> error while loading this page.</p>
                            <p>Basic Authentication Failure - Reason : AUTHENTICATED_FAILED</p>
                            <p><a href="/secure/MyJiraHome.jspa">Go to Jira home</a></p>
                        </div>
```

**Comment by cmoulliard** [comment]
Is this problem resolved ? @jacobdotcosta

**Comment by cmoulliard** [comment]
That fails for me using the snowdrop-bot credentials

```
user=snowdrop-jirabot
pwd='xxxxxx'
issue=468

java -jar target/uber-atlassian-1.0-SNAPSHOT.jar \
    -user ${user} \
    -password ${pwd} \
    -url https://issues.redhat.com \
    -cfg etc/release.yaml \
    -action get \
    -issue ENTSBT-${issue}
```

**Comment by jacobdotcosta** [comment]
It works with the bot...
```bash
$ java -jar target/uber-atlassian-1.0-SNAPSHOT.jar     -user ${user}     -password ${pwd}     -cfg etc/release.yaml     -action get     -url https://issues.redhat.com -issue ISSUE-###
```
...returned the whole contents of the issue.

**Comment by cmoulliard** [comment]
> At first attempt using Firefox JIRA showed a message to complete some configuration steps before actually being able to login

Can you improve this text please to mention that account should be linked/migrated ? @jacobdotcosta

**Comment by cmoulliard** [comment]
There is nevertheless a pribme as this JIRA service account cannot create or update all the needed fields s you get this error ?

```
Exception in thread "main" RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={duedate=Field 'duedate' cannot be set. It is not on the appropriate screen, or unknown.}, errorMessages=[]}]}
        at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.claim(DelegatingPromise.java:45)
        at dev.snowdrop.jira.atlassian.Client.createIssue(Client.java:92)
        at dev.snowdrop.jira.atlassian.Client.main(Client.java:39)
Caused by: RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={duedate=Field 'duedate' cannot be set. It is not on the appropriate screen, or unknown.}, errorMessages=[]}]}
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:176)
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:170)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:49)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:10)
        at io.atlassian.util.concurrent.Promises$OfStage.lambda$fold$4(Promises.java:332)
        at io.atlassian.util.concurrent.Promises.lambda$biFunction$7(Promises.java:422)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1.lambda$doCompleted$0(SettableFuturePromiseHttpPromiseAsyncClient.java:37)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:61)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:129)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
``` 

**REMARK**: This problem is similar to #7

**Comment by jacobdotcosta** [comment]
> Can you improve this text please to mention that account should be linked/migrated ? @jacobdotcosta

I didn't perform any linking to the legacy account, just skipped the process.

**Comment by cmoulliard** [comment]
To be able to create an issue, a user should be part of the `jira-users` group and perhaps others too - https://issues.redhat.com/plugins/servlet/project-config/ENTSBT/permissions

**Comment by jacobdotcosta** [comment]
> To be able to create an issue, a user should be part of the `jira-users` group and perhaps others too - https://issues.redhat.com/plugins/servlet/project-config/ENTSBT/permissions

The user can create issues (check [this](https://issues.redhat.com/browse/ENTSBT-469) ) but doesn't have access to the *Due Date* field. It only belongs to the `jira-users` group, he might need some more groups.

**Comment by cmoulliard** [comment]
I got this error during the process to create a JIRA issue

```
java -jar target/uber-atlassian-1.0-SNAPSHOT.jar \
>     -user ${user} \
>     -password ${pwd} \
>     -cfg etc/release.yaml \
>     -action create \
>     -url https://issues.redhat.com
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={duedate=Field 'duedate' cannot be set. It is not on the appropriate screen, or unknown.}, errorMessages=[]}]}
        at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.claim(DelegatingPromise.java:45)
        at dev.snowdrop.jira.atlassian.Client.createIssue(Client.java:92)
        at dev.snowdrop.jira.atlassian.Client.main(Client.java:39)
Caused by: RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={duedate=Field 'duedate' cannot be set. It is not on the appropriate screen, or unknown.}, errorMessages=[]}]}
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:176)
        at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:170)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:49)
        at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:10)
        at io.atlassian.util.concurrent.Promises$OfStage.lambda$fold$4(Promises.java:332)
        at io.atlassian.util.concurrent.Promises.lambda$biFunction$7(Promises.java:422)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1.lambda$doCompleted$0(SettableFuturePromiseHttpPromiseAsyncClient.java:37)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:61)
        at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:129)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
